"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-09
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("public_id", sa.String(64), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("environment", sa.String(32), nullable=False), sa.Column("consent_mode", sa.String(32), nullable=False), sa.Column("retention_days", sa.Integer(), nullable=False), sa.Column("sdk_config", sa.JSON(), nullable=False), sa.Column("url_redaction_rules", sa.JSON(), nullable=False), sa.Column("permitted_events", sa.JSON(), nullable=False), sa.Column("permitted_metadata", sa.JSON(), nullable=False), sa.Column("approved_support_urls", sa.JSON(), nullable=False), sa.Column("rate_limits", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_projects_public_id", "projects", ["public_id"], unique=True)
    op.create_table("project_origins", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("origin", sa.String(255), nullable=False), sa.UniqueConstraint("project_id", "origin"))
    op.create_index("ix_project_origins_project_id", "project_origins", ["project_id"])
    op.create_index("ix_project_origins_origin", "project_origins", ["origin"])
    op.create_table("admin_users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(255), nullable=False), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("mfa_secret", sa.String(128), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_admin_users_email", "admin_users", ["email"], unique=True)
    op.create_table("roles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(80), nullable=False), sa.Column("description", sa.String(255), nullable=True))
    op.create_index("ix_roles_name", "roles", ["name"], unique=True)
    op.create_table("permissions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("description", sa.String(255), nullable=True))
    op.create_index("ix_permissions_name", "permissions", ["name"], unique=True)
    op.create_table("admin_user_roles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("admin_user_id", sa.Integer(), sa.ForeignKey("admin_users.id"), nullable=False), sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id"), nullable=False), sa.UniqueConstraint("admin_user_id", "role_id"))
    op.create_index("ix_admin_user_roles_admin_user_id", "admin_user_roles", ["admin_user_id"])
    op.create_index("ix_admin_user_roles_role_id", "admin_user_roles", ["role_id"])
    op.create_table("project_settings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("key", sa.String(96), nullable=False), sa.Column("value", sa.JSON(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("project_id", "key"))
    op.create_index("ix_project_settings_project_id", "project_settings", ["project_id"])
    op.create_table("browser_visitors", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("external_id", sa.String(64), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("first_seen_at", sa.DateTime(), nullable=False), sa.Column("last_seen_at", sa.DateTime(), nullable=False), sa.Column("pseudonymous_ref", sa.String(255), nullable=True))
    op.create_index("ix_browser_visitors_external_id", "browser_visitors", ["external_id"], unique=True)
    op.create_table("browser_sessions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("external_id", sa.String(64), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("visitor_id", sa.Integer(), sa.ForeignKey("browser_visitors.id"), nullable=False), sa.Column("state", sa.Enum("CONNECTED","ACTIVE","IDLE","BACKGROUND","OFFLINE","DISCONNECTED","EXPIRED","CONSENT_WITHDRAWN","BLOCKED", name="sessionstate"), nullable=False), sa.Column("consent_state", sa.Enum("GRANTED","DENIED","WITHDRAWN","IMPLIED", name="consentstate"), nullable=False), sa.Column("public_ip_hash", sa.String(128), nullable=True), sa.Column("public_ip_anonymized", sa.String(64), nullable=True), sa.Column("country", sa.String(64), nullable=True), sa.Column("browser_family", sa.String(64), nullable=True), sa.Column("browser_version", sa.String(64), nullable=True), sa.Column("operating_system", sa.String(64), nullable=True), sa.Column("device_category", sa.String(32), nullable=True), sa.Column("current_origin", sa.String(255), nullable=True), sa.Column("current_route", sa.String(1024), nullable=True), sa.Column("referrer_origin", sa.String(255), nullable=True), sa.Column("sdk_version", sa.String(32), nullable=True), sa.Column("app_version", sa.String(64), nullable=True), sa.Column("first_seen_at", sa.DateTime(), nullable=False), sa.Column("last_seen_at", sa.DateTime(), nullable=False), sa.Column("disconnected_at", sa.DateTime(), nullable=True))
    op.create_index("ix_browser_sessions_external_id", "browser_sessions", ["external_id"], unique=True)
    op.create_index("ix_sessions_project_state_last", "browser_sessions", ["project_id", "state", "last_seen_at"])
    op.create_table("session_capabilities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("browser", sa.JSON(), nullable=False), sa.Column("display", sa.JSON(), nullable=False), sa.Column("graphics", sa.JSON(), nullable=False), sa.Column("network", sa.JSON(), nullable=False), sa.Column("page", sa.JSON(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index("ix_session_capabilities_session_id", "session_capabilities", ["session_id"], unique=True)
    op.create_table("session_connections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("connected_at", sa.DateTime(), nullable=False), sa.Column("disconnected_at", sa.DateTime(), nullable=True), sa.Column("transport", sa.String(32), nullable=False), sa.Column("latency_summary", sa.JSON(), nullable=False))
    op.create_index("ix_session_connections_session_id", "session_connections", ["session_id"])
    op.create_table("session_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("event_id", sa.String(64), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("category", sa.String(64), nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_session_events_event_id", "session_events", ["event_id"], unique=True)
    op.create_index("ix_events_session_time", "session_events", ["session_id", "created_at"])
    op.create_table("performance_metrics", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("route", sa.String(1024), nullable=True), sa.Column("metrics", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_perf_session_time", "performance_metrics", ["session_id", "created_at"])
    op.create_table("application_errors", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=True), sa.Column("fingerprint", sa.String(128), nullable=False), sa.Column("message", sa.String(512), nullable=False), sa.Column("sanitized_stack", sa.Text(), nullable=True), sa.Column("source_file", sa.String(255), nullable=True), sa.Column("line", sa.Integer(), nullable=True), sa.Column("column", sa.Integer(), nullable=True), sa.Column("route", sa.String(1024), nullable=True), sa.Column("occurrence_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_application_errors_fingerprint", "application_errors", ["fingerprint"])
    op.create_index("ix_errors_project_time", "application_errors", ["project_id", "created_at"])
    op.create_table("diagnostic_actions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("action_id", sa.String(64), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("requested_by_admin_id", sa.Integer(), sa.ForeignKey("admin_users.id"), nullable=True), sa.Column("action_type", sa.String(64), nullable=False), sa.Column("parameters", sa.JSON(), nullable=False), sa.Column("status", sa.Enum("PENDING","SENT","COMPLETED","FAILED","EXPIRED","CANCELLED", name="actionstatus"), nullable=False), sa.Column("user_visible_description", sa.String(255), nullable=False), sa.Column("expires_at", sa.DateTime(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_diagnostic_actions_action_id", "diagnostic_actions", ["action_id"], unique=True)
    op.create_table("diagnostic_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("action_id", sa.Integer(), sa.ForeignKey("diagnostic_actions.id"), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("result", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("tags", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("color", sa.String(16), nullable=False))
    op.create_table("session_tags", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("tag_id", sa.Integer(), sa.ForeignKey("tags.id"), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("session_id", "tag_id"))
    op.create_index("ix_session_tags_session_id", "session_tags", ["session_id"])
    op.create_index("ix_session_tags_tag_id", "session_tags", ["tag_id"])
    op.create_table("session_notes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=False), sa.Column("admin_user_id", sa.Integer(), sa.ForeignKey("admin_users.id"), nullable=True), sa.Column("body", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("alert_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("rule_type", sa.String(80), nullable=False), sa.Column("config", sa.JSON(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("cooldown_seconds", sa.Integer(), nullable=False))
    op.create_index("ix_alert_rules_project_id", "alert_rules", ["project_id"])
    op.create_index("ix_alert_rules_rule_type", "alert_rules", ["rule_type"])
    op.create_table("alerts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("alert_rule_id", sa.Integer(), sa.ForeignKey("alert_rules.id"), nullable=True), sa.Column("status", sa.String(32), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("title", sa.String(180), nullable=False), sa.Column("details", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("resolved_at", sa.DateTime(), nullable=True))
    op.create_index("ix_alerts_project_id", "alerts", ["project_id"])
    op.create_index("ix_alerts_status", "alerts", ["status"])
    op.create_table("consent_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("visitor_id", sa.Integer(), sa.ForeignKey("browser_visitors.id"), nullable=True), sa.Column("session_id", sa.Integer(), sa.ForeignKey("browser_sessions.id"), nullable=True), sa.Column("consent_state", sa.Enum("GRANTED","DENIED","WITHDRAWN","IMPLIED", name="consentstate"), nullable=False), sa.Column("consent_version", sa.String(64), nullable=True), sa.Column("source", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_consent_records_project_id", "consent_records", ["project_id"])
    op.create_table("exports", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("admin_user_id", sa.Integer(), sa.ForeignKey("admin_users.id"), nullable=True), sa.Column("export_type", sa.String(64), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("format", sa.String(16), nullable=False), sa.Column("filters", sa.JSON(), nullable=False), sa.Column("signed_url_expires_at", sa.DateTime(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_exports_project_id", "exports", ["project_id"])
    op.create_table("data_deletion_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("visitor_external_id", sa.String(64), nullable=True), sa.Column("status", sa.String(32), nullable=False), sa.Column("requested_by_admin_id", sa.Integer(), sa.ForeignKey("admin_users.id"), nullable=True), sa.Column("completed_at", sa.DateTime(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_data_deletion_requests_project_id", "data_deletion_requests", ["project_id"])
    op.create_table("sdk_versions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("version", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("release_notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_sdk_versions_version", "sdk_versions", ["version"], unique=True)
    op.create_table("audit_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("admin_user_id", sa.Integer(), sa.ForeignKey("admin_users.id"), nullable=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=True), sa.Column("action", sa.String(96), nullable=False), sa.Column("target_type", sa.String(64), nullable=True), sa.Column("target_id", sa.String(128), nullable=True), sa.Column("ip", sa.String(64), nullable=True), sa.Column("result", sa.String(32), nullable=False), sa.Column("details", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"])


def downgrade() -> None:
    for table in ["audit_logs", "sdk_versions", "data_deletion_requests", "exports", "consent_records", "alerts", "alert_rules", "session_notes", "session_tags", "tags", "diagnostic_results", "diagnostic_actions", "application_errors", "performance_metrics", "session_events", "session_connections", "session_capabilities", "browser_sessions", "browser_visitors", "project_settings", "admin_user_roles", "permissions", "roles", "admin_users", "project_origins", "projects"]:
        op.drop_table(table)
